### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by EliasGrim** [google-developer-training/android-basics-kotlin-dessert-clicker-app#13]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#4
**In which task and step of the codelab can this issue be found?**
Part 5 explore configuration changes

**Describe the problem**

Data loss on device rotation
The app works fine from 0 to 5 but when the image change, from 6 or more the app stop working

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by amberream** [comment]
It's actually step 7 where we add the call to showCurrentDessert().  But my app was also crashing on rotate after adding the call to this method.  Turns out I missed the part in step 2 where it said to add the lines to restore the variables and call showCurrentDessert() AFTER setting up the binding in onCreate.  showCurrentDessert() uses the binding, so it's necessary to set up the binding first. Also be sure to restore the values in onCreate() before using the binding to set the values to the revenue and amountSold text views.

**Comment by KaungZM** [comment]
> It's actually step 7 where we add the call to showCurrentDessert(). But my app was also crashing on rotate after adding the call to this method. Turns out I missed the part in step 2 where it said to add the lines to restore the variables and call showCurrentDessert() AFTER setting up the binding in onCreate. showCurrentDessert() uses the binding, so it's necessary to set up the binding first. Also be sure to restore the values in onCreate() before using the binding to set the values to the revenue and amountSold text views.

Thank you. This is exactly what I missed too. I added if() block before binding was initialized and that's why the app was crashing.
