### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by JenStep** [google-developer-training/android-basics-kotlin-dessert-clicker-app#18]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#4

**In which task and step of the codelab can this issue be found?**
Use onCreate() to restore bundle data

**Describe the problem**
Instruction code is missing nullable declaration. Should be:
```
override fun onCreate(savedInstanceState: Bundle?) {
```

**Steps to reproduce?**
N/A

**Versions**
N/A

**Additional information**
Screenshot
![image](https://user-images.githubusercontent.com/32082395/112930839-e0dad580-90cf-11eb-8340-54db67ce681b.png)

**Comment by osuleymanova** [comment]
@JenStep 
Thank you for reaching out to us. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#4
