### ISSUE TITLE
Android Basics: Activity Lifecycle - Description should mention rotation lock

### ISSUE THREAD

**Issue by charles-allen** [google-developer-training/android-basics-kotlin-dessert-clicker-app#19]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle#4

**In which task and step of the codelab can this issue be found?**
"5. Explore configuration changes"

**Describe the problem**
Under section "Data loss on device rotation", step 2, we're instructed to rotate the device or emulator into landscape mode to observe a configuration change.

On my emulator, _screen rotation was locked by default_, preventing a true screen rotation (configuration change) from occurring, and resulting in no log messages. Since the device itself _did_ rotate, I was momentarily confused.

Suggested:
- Add a step to ensure rotation lock is disabled
- Add a screenshot of the emulator _after_ rotation

**Steps to reproduce?**
1. Click rotate

**Expected**
- Device rotates
- Log messages representing activity destruction and recreation.

**Actual**
- Device rotates (but layout does not)
- No log messages

**Additional information**
The device itself does rotate, so I believed I had followed the instructions correctly:
![Screenshot_1617617326](https://user-images.githubusercontent.com/31621095/113563562-17fe3900-9632-11eb-9f1a-f3eb0c0908d2.png)

**Comment by danielslabo** [comment]
Commenting to say, me too! It's my first time reviewing the git repo of something, looking if there's an issue because the tutorial I'm following isn't matching with what I'm seeing, and finding an issue that describes it. This issue lost me 10-20 minutes of re-reviewing my steps to make sure I didn't do something wrong, before realizing my emulator turned but not the app (because of the lock).
